export const AUTH_FORM_LOGIN = 'AUTH_FORM_LOGIN';
export const AUTH_FORM_LOGIN_ERROR = 'AUTH_FORM_LOGIN_ERROR';

export const AUTH_FORM_FORGOT_PASSWORD = 'AUTH_FORGOT_PASSWORD';
export const AUTH_FORM_FORGOT_PASSWORD_ERROR = 'AUTH_FORGOT_PASSWORD_ERROR';
